server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: test
  flyway:
    enabled: false

  application:
    name: 3D Webshop

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: HSQL
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

  datasource:
    jdbcUrl: jdbc:hsqldb:mem:ecommerce3d
    driverClassName: org.h2.Driver
    username: sa
    password:

# AWS S3 configuration
aws:
  endpointUrl: 'test'
  access_key_id: 'test'
  secret_access_key: 'test'
  s3:
    bucket: 'test'
    region: 'test'

application:
  jwt:
    secretKey: 'testsecuretestsecuretestsecuretestsecuretestsecuretestsecure'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14

